import {test} from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {assertOwner,requireAdmin,effectiveStatus,day,jobSchema,vehicleSchema,invoiceSchema,validEvent,applyPayment,integrity,todayBogota} from '../server/domain';
test('un cliente no puede leer el trabajo de otro ni convertirse en administrador',()=>{assert.throws(()=>assertOwner({uid:'alice',admin:false},'bob'));assert.throws(()=>requireAdmin({admin:false}));assert.doesNotThrow(()=>assertOwner({uid:'alice',admin:false},'alice'));assert.doesNotThrow(()=>assertOwner({uid:'admin',admin:true},'bob'));});
test('fechas reales y zona horaria de Colombia',()=>{assert.equal(day.safeParse('2026-02-30').success,false);assert.equal(day.safeParse('2026-02-28').success,true);assert.equal(todayBogota(new Date('2026-09-12T02:00:00Z')),'2026-09-11');});
test('un trabajo entregado no vuelve a atrasado',()=>{assert.equal(effectiveStatus({status:'en_proceso',deadline:'2026-09-01'},'2026-09-11'),'atrasado');assert.equal(effectiveStatus({status:'entregado',deadline:'2026-09-01'},'2026-09-11'),'entregado');assert.equal(effectiveStatus({status:'programado',deadline:'2026-09-11'},'2026-09-11'),'programado');});
test('campos extra de privilegios y montos inválidos son rechazados',()=>{const v={ownerId:'alice',plate:'ABC123',brand:'Toyota',model:'Prado',year:2024};assert.equal(vehicleSchema.safeParse({...v,admin:true}).success,false);assert.equal(vehicleSchema.safeParse(v).success,true);assert.equal(invoiceSchema.safeParse({ownerId:'alice',jobId:'job1',description:'Servicio',amountCents:-100,dueDate:'2026-09-11'}).success,false);});
test('revisión anterior a la entrega es inválida',()=>{assert.equal(jobSchema.safeParse({ownerId:'alice',vehicleId:'v1',service:'Detailing',status:'listo',deadline:'2026-09-20',nextReview:'2026-09-10'}).success,false);});
function signed(){const event:any={event:'transaction.updated',environment:'test',timestamp:1789000000,data:{transaction:{id:'tx-1',status:'APPROVED',amount_in_cents:100000}},signature:{properties:['transaction.id','transaction.status','transaction.amount_in_cents']}};event.signature.checksum=createHash('sha256').update('tx-1APPROVED1000001789000000secret').digest('hex');return event;}
test('webhook verifica firma y rechaza alteración de monto o firma incompleta',()=>{const event=signed();assert.equal(validEvent(event,'secret'),true);event.data.transaction.amount_in_cents=1;assert.equal(validEvent(event,'secret'),false);assert.equal(validEvent({...signed(),signature:{properties:[],checksum:'a'.repeat(64)}},'secret'),false);assert.equal(validEvent(signed(),''),false);});
test('pago solo se concilia con monto, referencia y moneda exactos',()=>{const invoice={reference:'DE-1',amountCents:100000,status:'pending'};const t={reference:'DE-1',amount_in_cents:100000,currency:'COP',status:'APPROVED',id:'tx1'};assert.equal(applyPayment(invoice,t).status,'paid');for(const wrong of [{...t,currency:'USD'},{...t,reference:'DE-2'},{...t,amount_in_cents:1}])assert.throws(()=>applyPayment(invoice,wrong));});
test('repetir webhook o recibir un rechazo posterior no revierte un pago',()=>{const invoice={reference:'DE-1',amountCents:100000,status:'paid',transactionId:'tx1'};const t={reference:'DE-1',amount_in_cents:100000,currency:'COP',status:'DECLINED',id:'tx1'};assert.deepEqual(applyPayment(invoice,t),invoice);});
test('firma del checkout es calculada en servidor',()=>{assert.equal(integrity('DE-1',100000,'COP','secret'),createHash('sha256').update('DE-1100000COPsecret').digest('hex'));});
