import {accessHeader} from './branding';
import {emailLogin,resetPassword,phoneEnabled,phoneCode,confirmPhone,refreshVerification,resendVerification,api} from './client';
export const googleLogo='<svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.39-.18-2.05H12v3.88h5.38a4.6 4.6 0 0 1-2 3.02v2.51h3.24c1.9-1.75 2.98-4.33 2.98-7.36Z"/><path fill="#34A853" d="M12 22c2.7 0 4.96-.9 6.62-2.42l-3.24-2.51c-.9.6-2.05.96-3.38.96-2.6 0-4.81-1.76-5.6-4.12H3.06v2.59A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 13.91a6 6 0 0 1 0-3.82V7.5H3.06a10 10 0 0 0 0 9l3.34-2.59Z"/><path fill="#EA4335" d="M12 5.97c1.47 0 2.79.5 3.83 1.5L18.7 4.6A9.6 9.6 0 0 0 12 2a10 10 0 0 0-8.94 5.5l3.34 2.59A6 6 0 0 1 12 5.97Z"/></svg>';
const error=(e:unknown)=>{const code=(e as {code?:string})?.code;return code==='auth/invalid-credential'?'Revisa el correo y la contraseña.':code==='auth/email-already-in-use'?'No se pudo crear la cuenta. Intenta ingresar o recuperar la contraseña.':code==='auth/too-many-requests'?'Demasiados intentos. Espera unos minutos.':code==='auth/weak-password'?'Utiliza una contraseña de al menos 12 caracteres.':code?'No se pudo completar el acceso. Revisa tus datos e inténtalo de nuevo.':e instanceof Error?e.message:'No se pudo completar la operación.';};
export function mountAccess(host:HTMLElement,enabled:boolean){
 const panel=document.createElement('div');panel.className='email-access';host.insertBefore(panel,host.querySelector('.fine'));
 panel.innerHTML=`<div class="access-divider">o con tu correo electrónico</div><form id="email-access"><label>Correo electrónico<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><button class="primary wide" ${enabled?'':'disabled'}>Ingresar con correo</button><button type="button" class="secondary wide" id="register-email">Crear una cuenta</button><button type="button" class="text-button" id="reset-email">Olvidé mi contraseña</button></form><details><summary>Ingresar con número de teléfono</summary>${phoneEnabled?'<form id="phone-access"><label>Teléfono con indicativo<input name="phone" type="tel" placeholder="+573001234567" autocomplete="tel" required></label><p class="fine">Google procesa tu número para verificar tu identidad y prevenir abusos. Al solicitar el código aceptas recibir un SMS de verificación.</p><div id="phone-recaptcha"></div><button class="secondary" '+(enabled?'':'disabled')+'>Enviar código SMS</button></form><form id="phone-confirm" hidden><label>Código SMS<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></label><button class="primary">Verificar código</button></form>':'<p class="fine">El acceso por SMS estará disponible próximamente. Por ahora utiliza Google o correo electrónico.</p>'}</details><p class="access-message" role="status"></p>`;
 const message=panel.querySelector<HTMLElement>('.access-message')!;const form=panel.querySelector<HTMLFormElement>('#email-access')!;let register=false;
 const run=async(fn:()=>Promise<void>)=>{const buttons=panel.querySelectorAll<HTMLButtonElement>('button');buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){message.textContent=error(e);}finally{buttons.forEach(b=>b.disabled=!enabled);}};
 panel.querySelector('#register-email')!.addEventListener('click',()=>{register=!register;form.querySelector('button')!.textContent=register?'Crear cuenta con correo':'Ingresar con correo';panel.querySelector('#register-email')!.textContent=register?'Ya tengo cuenta':'Crear una cuenta';const password=form.elements.namedItem('password') as HTMLInputElement;password.minLength=register?12:1;password.autocomplete=register?'new-password':'current-password';message.textContent=register?'Usa al menos 12 caracteres. Verificaremos tu correo y luego te pediremos la placa.':'';});
 form.addEventListener('submit',e=>{e.preventDefault();void run(async()=>{if(register&&!document.querySelector<HTMLInputElement>('#consent')?.checked)throw new Error('Acepta el aviso de privacidad para crear tu cuenta.');const fields=new FormData(form);await emailLogin(String(fields.get('email')),String(fields.get('password')),register);});});
 panel.querySelector('#reset-email')!.addEventListener('click',()=>void run(async()=>{const input=form.elements.namedItem('email') as HTMLInputElement;if(!input.reportValidity())return;try{await resetPassword(input.value);}catch{}message.textContent='Si el correo corresponde a una cuenta, recibirás instrucciones para recuperar el acceso.';}));
 panel.querySelector('#phone-access')?.addEventListener('submit',e=>{e.preventDefault();void run(async()=>{await phoneCode(String(new FormData(e.target as HTMLFormElement).get('phone')));panel.querySelector<HTMLFormElement>('#phone-confirm')!.hidden=false;message.textContent='Escribe el código que recibiste por SMS.';});});
 panel.querySelector('#phone-confirm')?.addEventListener('submit',e=>{e.preventDefault();void run(async()=>{await confirmPhone(String(new FormData(e.target as HTMLFormElement).get('code')));});});
}
export function registrationView(root:HTMLElement,verified:boolean,done:()=>Promise<void>){
 root.innerHTML=`${accessHeader}<div class="registration-scene"><main class="registration panel"><span class="eyebrow">TU CUENTA</span><h1>${verified?'Registra tu vehículo':'Verifica tu correo'}</h1>${verified?'<p>Indica la placa de tu vehículo. El equipo comprobará la asociación antes de mostrar su historial.</p><form><label>Placa del vehículo<input name="plate" placeholder="ABC123" pattern="[A-Za-z0-9-]{4,10}" minlength="4" maxlength="10" autocomplete="off" required></label><label class="consent"><input name="consent" type="checkbox" required><span>Acepto el <a href="/portal/privacidad.html" target="_blank" rel="noopener">aviso de privacidad</a> y el tratamiento de mis datos para gestionar mis servicios.</span></label><button class="primary">Completar registro</button></form>':'<p>Abre el enlace de verificación enviado a tu correo y vuelve aquí para continuar.</p><button class="primary" id="verified-email">Ya verifiqué mi correo</button><button class="secondary" id="resend-email">Reenviar verificación</button>'}<p role="status" id="registration-message"></p><button class="text-button" id="registration-exit">Salir de esta cuenta</button></main></div>`;
 const message=root.querySelector<HTMLElement>('#registration-message')!;
 root.querySelector('#registration-exit')!.addEventListener('click',async()=>{const {logout}=await import('./client');await logout();});
 root.querySelector('#verified-email')?.addEventListener('click',async()=>{try{if(await refreshVerification())await done();else message.textContent='Tu correo aún no está verificado.';}catch(e){message.textContent=error(e);}});
 root.querySelector('#resend-email')?.addEventListener('click',async()=>{try{await resendVerification();message.textContent='Enlace enviado. Revisa también la carpeta de spam.';}catch(e){message.textContent=error(e);}});
 root.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.target as HTMLFormElement;const button=form.querySelector('button')!;button.disabled=true;try{await api('profile',{consent:true,plate:String(new FormData(form).get('plate')).trim().toUpperCase()});await done();}catch(e){message.textContent=error(e);button.disabled=false;}});
}
