// Imported only in development, on explicit user action. No remote calls.
export function demoData(admin=false){const now=new Date();const day=(offset:number)=>new Date(now.getTime()+offset*86400000).toISOString().slice(0,10);return {
 me:{uid:'demo-client',name:admin?'Equipo Detailing':'Camila · ejemplo',email:'cliente@ejemplo.test',admin,profile:{notifications:false}},
 users:[{id:'demo-client',name:'Camila · ejemplo',email:'cliente@ejemplo.test'}],
 vehicles:[{id:'car-1',ownerId:'demo-client',brand:'Toyota',model:'Prado',plate:'DEMO01',year:2024,color:'Gris'},{id:'car-2',ownerId:'demo-client',brand:'Mazda',model:'CX-5',plate:'DEMO02',year:2023,color:'Blanco'}],
 jobs:[{id:'job-1',ownerId:'demo-client',vehicleId:'car-1',service:'Protección anticorrosiva',status:'en_proceso',deadline:day(2),appointmentAt:`${day(1)}T14:00:00.000Z`,nextReview:day(60),warrantyUntil:day(365),notes:'Revisión de superficies y aplicación de protección. Datos de demostración.',assignedTo:'Equipo técnico',updatedAt:now.toISOString(),checklist:[{label:'Inspección de ingreso',done:true},{label:'Preparación de superficies',done:true},{label:'Control de calidad',done:false}]},{id:'job-2',ownerId:'demo-client',vehicleId:'car-2',service:'Detailing interior y exterior',status:'entregado',deadline:day(-20),appointmentAt:'',nextReview:day(7),warrantyUntil:'',notes:'Trabajo de ejemplo entregado.',assignedTo:'',updatedAt:now.toISOString(),checklist:[{label:'Control de calidad',done:true}]}],
 invoices:[{id:'invoice-1',jobId:'job-1',ownerId:'demo-client',description:'Protección anticorrosiva · ejemplo',amountCents:85000000,status:'pending',reference:'DE-DEMO',dueDate:day(2)}],
 requests:[{id:'request-1',ownerId:'demo-client',vehicleId:'car-2',reason:'Quisiera programar mi próxima revisión.',preferredDate:day(7),status:'pendiente'}],
 notifications:[{id:'notice-1',ownerId:'demo-client',title:'Tu vehículo está en buenas manos',body:'Ya iniciamos el trabajo de protección. Este es un aviso de demostración.',read:false,updatedAt:now.toISOString()}],audit:[]};}
