import {brandLink,accessHeader} from './branding';
import {googleLogo,mountAccess,registrationView} from './access';
import './style.css';
import './brand.css';
import {api,setup,login,logout,ready,notifications,compressPhoto} from './client';
type Row=Record<string,any>;
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(v/100);
const date=(v:string)=>v?new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',year:'numeric',timeZone:'America/Bogota'}).format(new Date(v.length===10?v+'T12:00:00-05:00':v)):'Por definir';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const stateLabel=(j:Row)=>!['listo','entregado','cancelado'].includes(j.status)&&j.deadline<today()?'atrasado':j.status;
const labels:Row={programado:'Programado',en_proceso:'En proceso',listo:'Listo para entregar',entregado:'Entregado',atrasado:'Atrasado',cancelado:'Cancelado',pending:'Pendiente',paid:'Pagado',pendiente:'Pendiente',atendida:'Atendida',rechazada:'Rechazada'};
const pill=(s:string)=>`<span class="pill ${esc(s)}">${esc(labels[s]||s)}</span>`;
let me:Row|null=null,demo=false,busy=false,serverStatus:Row={},page='resumen',query='';
let data:Record<string,Row[]>={vehicles:[],jobs:[],invoices:[],requests:[],notifications:[],users:[],audit:[]};
let cursors:Record<string,string|null>={};let installPrompt:any;
const toast=(text:string)=>{document.querySelector('#toast')!.textContent=text;setTimeout(()=>{document.querySelector('#toast')!.textContent='';},6500);};
const vehicle=(id:string)=>data.vehicles.find(v=>v.id===id);
const carName=(id:string)=>{const v=vehicle(id);return v?`${v.brand} ${v.model} · ${v.plate}`:'Vehículo registrado';};
const clientName=(id:string)=>data.users.find(u=>u.id===id)?.name||'Cliente';
function view(){const value=location.hash.slice(1).split('?')[0];page=['resumen','vehiculos','trabajos','mantenimientos','pagos','avisos','ajustes','clientes','solicitudes','actividad'].includes(value)?value:'resumen';if(!me?.admin&&['clientes','solicitudes','actividad'].includes(page))page='resumen';query='';render();window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',view);
window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();installPrompt=e;if(me)render();});
window.addEventListener('appinstalled',()=>{installPrompt=null;toast('App instalada. Ya puedes abrirla desde tu pantalla de inicio.');});
window.addEventListener('offline',()=>toast('Sin conexión. Los cambios necesitan internet.'));
const btn=(action:string,text:string,kind='secondary',attrs='')=>`<button type="button" class="${kind}" data-action="${action}" ${attrs}>${text}</button>`;
function loginView(){root.innerHTML=`${accessHeader}<main class="login"><div class="login-visual">${brandLink}<div><span class="eyebrow">EL CUIDADO CONTINÚA</span><h1>Tu vehículo.<br>Siempre al día.</h1><p>El próximo mantenimiento, cada detalle del trabajo y la tranquilidad de tenerlo todo a mano.</p></div><div class="login-bottom"><span>01 / HISTORIAL</span><span>02 / REVISIONES</span><span>03 / CUIDADO</span></div></div><section class="login-panel"><a href="/" class="back">← Volver al sitio web</a><div class="login-box"><span class="eyebrow">PORTAL DE CLIENTES</span><h2>Bienvenido a<br>tu espacio.</h2><p>Consulta tus vehículos y servicios con tu cuenta de Google o tu correo electrónico.</p><label class="consent"><input type="checkbox" id="consent"> <span>He leído el <a href="/portal/privacidad.html" target="_blank" rel="noopener">aviso de privacidad del portal</a> y autorizo el tratamiento de mis datos para gestionar mis servicios.</span></label>${btn('login',googleLogo+' Continuar con Google','primary wide',!ready||!serverStatus.configured?'disabled':'')}<p class="fine">Tu historial es privado. Al ingresar por primera vez, el equipo asociará tus vehículos a tu cuenta.</p>${!ready||!serverStatus.configured?'<div class="notice">Estamos preparando el portal. El acceso estará disponible cuando finalice la configuración.</div>':''}${import.meta.env.DEV?`<div class="demo-entry"><p>Vista previa local · datos de ejemplo</p>${btn('demo-client','Explorar como cliente')}${btn('demo-admin','Explorar administración')}</div>`:''}</div><footer>Detailing Experts · Cuidamos cada detalle.</footer></section></main>`;bind();mountAccess(root.querySelector<HTMLElement>('.login-box')!,ready&&!!serverStatus.configured);}
async function load(){if(demo)return;const collections=['vehicles','jobs','invoices','requests','notifications',...(me?.admin?['users','audit']:[])];const results=await Promise.all(collections.map(async c=>({c,result:await api('list',undefined,{collection:c})})));for(const {c,result}of results){data[c]=result.items;cursors[c]=result.nextCursor;}}
const empty=(title:string,text:string)=>`<div class="empty"><span class="empty-icon">◇</span><h3>${title}</h3><p>${text}</p></div>`;
function jobCard(j:Row){return `<button class="job-card" data-action="job-detail" data-id="${esc(j.id)}"><div class="row">${pill(stateLabel(j))}<span class="small">${date(j.deadline)}</span></div><h3>${esc(j.service)}</h3><p>${esc(carName(j.vehicleId))}</p><div class="job-foot"><span>${me?.admin?esc(clientName(j.ownerId)):'Ver trabajo y fotografías'}</span><span>↗</span></div></button>`;}
function stats(){const open=data.jobs.filter(j=>!['entregado','cancelado'].includes(j.status));const overdue=open.filter(j=>stateLabel(j)==='atrasado');return `<div class="stats"><article><span>${me?.admin?'Trabajos activos':'Mis vehículos'}</span><strong>${me?.admin?open.length:data.vehicles.length.toString().padStart(2,'0')}</strong><small>${me?.admin?'En la página cargada':'Vinculados a tu cuenta'}</small></article><article><span>${me?.admin?'Necesitan atención':'Próximas revisiones'}</span><strong>${me?.admin?overdue.length:data.jobs.filter(j=>j.nextReview&&j.nextReview>=today()).length}</strong><small>${me?.admin?'Con fecha límite vencida':'Cuidado programado'}</small></article><article><span>Pagos pendientes</span><strong class="amount">${money(data.invoices.filter(i=>i.status==='pending').reduce((s,i)=>s+i.amountCents,0))}</strong><small>${me?.admin?'Cobros de la página cargada':'Saldo por servicios registrados'}</small></article></div>`;}
function overview(){const next=data.jobs.filter(j=>j.nextReview&&j.status!=='cancelado').sort((a,b)=>a.nextReview.localeCompare(b.nextReview))[0];return `${stats()}<div class="overview-grid"><section><div class="section-title"><h2>${me?.admin?'En el taller':'Tus trabajos'}</h2><a href="#trabajos">Ver todos ↗</a></div><div class="cards">${data.jobs.slice(0,4).map(jobCard).join('')||empty('Todo comienza con tu primer servicio','Aquí verás el avance y el historial de los trabajos.')}</div></section><aside><div class="review-card"><span class="eyebrow">PRÓXIMO CUIDADO</span><div class="calendar-mark">↗</div><h2>${next?date(next.nextReview):'Un cuidado que continúa.'}</h2><p>${next?`${esc(next.service)}<br>${esc(carName(next.vehicleId))}`:'El equipo registrará aquí la próxima revisión de tu vehículo.'}</p><a class="primary" href="#mantenimientos">${me?.admin?'Revisar agenda':'Ver mantenimientos'} →</a></div><div class="help-card"><span class="eyebrow">ESTAMOS CERCA</span><h3>¿Necesitas ayuda?</h3><p>Habla con el equipo para resolver cualquier duda sobre tu servicio.</p><a href="https://wa.me/573016501515" target="_blank" rel="noopener noreferrer">Escribir por WhatsApp ↗</a></div></aside></div>`;}
function vehicles(){return `<div class="section-title"><p>La información de cada vehículo, en un solo lugar.</p>${me?.admin?btn('new-vehicle','+ Registrar vehículo','primary'):''}</div><div class="cards">${data.vehicles.filter(matches).map(v=>`<article class="vehicle-card"><div class="row"><span class="eyebrow">${esc(v.brand)}</span><span class="plate">${esc(v.plate)}</span></div><svg viewBox="0 0 240 100" aria-hidden="true" class="car-art"><path d="M30 62 44 37Q48 31 61 31h86q13 0 25 17l25 8q14 3 14 17v7H22V69q0-6 8-7z"/><path d="M59 35 48 57h112l-18-22z"/><circle cx="63" cy="78" r="13"/><circle cx="170" cy="78" r="13"/></svg><h2>${esc(v.model)}</h2><p>${esc(v.year)} · ${esc(v.color||'Color no registrado')}</p>${me?.admin?`<p>${esc(clientName(v.ownerId))}</p>`:''}<a href="#trabajos">Consultar trabajos →</a></article>`).join('')||empty('Aún no hay vehículos','Después de tu registro, el equipo vinculará tus vehículos. No necesitas publicar tu placa ni tus documentos.')}</div>${more('vehicles')}`;}
function matches(row:Row){return JSON.stringify(row).toLowerCase().includes(query.toLowerCase());}
function more(collection:string){return cursors[collection]?btn('load-more','Cargar más registros','secondary',`data-collection="${collection}"`):'';}
function jobs(){return `<div class="section-title"><p>Avances, fechas de entrega y control de calidad.</p>${me?.admin?btn('new-job','+ Nuevo trabajo','primary'):''}</div><div class="filters">${['todos','programado','en_proceso','listo','atrasado','entregado'].map(s=>btn('filter',labels[s]||'Todos','chip',`data-filter="${s}"`)).join('')}</div><div class="cards" id="job-list">${data.jobs.filter(matches).map(jobCard).join('')||empty('Sin trabajos registrados','Los servicios aparecerán aquí cuando el equipo los registre.')}</div>${more('jobs')}`;}
function maintenance(){const rows=data.jobs.filter(j=>(j.nextReview||j.appointmentAt)&&j.status!=='cancelado').sort((a,b)=>(a.nextReview||a.appointmentAt).localeCompare(b.nextReview||b.appointmentAt));return `<div class="section-title"><p>Una revisión recomendada no equivale a una cita confirmada.</p>${!me?.admin?btn('new-request','Solicitar una cita','primary'):btn('new-job','Programar trabajo','primary')}</div><div class="timeline">${rows.map(j=>`<article><div class="timeline-date">${date(j.nextReview||j.appointmentAt)}</div><div><span class="eyebrow">${j.nextReview?'REVISIÓN RECOMENDADA':'CITA CONFIRMADA'}</span><h3>${esc(j.service)}</h3><p>${esc(carName(j.vehicleId))}</p>${j.appointmentAt?`<p>Cita: ${date(j.appointmentAt)} · ${new Date(j.appointmentAt).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit',timeZone:'America/Bogota'})}</p>`:''}${j.nextReview&&j.nextReview<today()?pill('atrasado'):''}</div>${btn('job-detail','Ver detalle','secondary',`data-id="${esc(j.id)}"`)}</article>`).join('')||empty('Tu agenda está al día','Cuando haya una revisión o una cita, la encontrarás aquí.')}</div>${!me?.admin?`<h2 class="spaced">Mis solicitudes</h2>${requestsList()}`:''}`;}
function payments(){return `<div class="section-title"><p>Consulta tus cobros y los pagos confirmados.</p>${me?.admin?btn('new-invoice','+ Crear cobro','primary'):''}</div>${!serverStatus.payments?'<div class="notice">Los pagos con tarjeta aún no están habilitados. El equipo te indicará cómo pagar mientras activamos Wompi.</div>':''}<div class="invoice-list">${data.invoices.filter(matches).map(i=>`<article><div><span class="eyebrow">${esc(i.reference)}</span><h3>${esc(i.description)}</h3><p>Vence: ${date(i.dueDate)}</p>${pill(i.status)}</div><div class="invoice-amount"><strong>${money(i.amountCents)}</strong>${i.status==='pending'?btn('pay',serverStatus.payments?'Pagar con Wompi ↗':'Pago en línea pendiente','primary',`data-id="${esc(i.id)}" ${!serverStatus.payments||demo?'disabled':''}`):'<span class="paid-label">✓ Pago verificado</span>'}</div></article>`).join('')||empty('Sin cobros pendientes','Los cobros emitidos por el equipo aparecerán aquí.')}</div>${more('invoices')}`;}
function notices(){return `<div class="notice-list">${data.notifications.map(n=>`<article class="${n.read?'read':''}"><span class="notice-dot"></span><div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><small>${date(n.updatedAt)}</small></div>${!n.read?btn('read','Marcar como leído','secondary',`data-id="${esc(n.id)}"`):'<span class="small">Leído</span>'}</article>`).join('')||empty('Todo al día','Aquí aparecerán actualizaciones de tus trabajos y revisiones.')}</div>${more('notifications')}`;}
function requestsList(){return data.requests.filter(matches).map(r=>`<article class="request-card"><div class="row">${pill(r.status)}<span class="small">Fecha solicitada: ${date(r.preferredDate)}</span></div><h3>${esc(carName(r.vehicleId))}</h3><p>${esc(r.reason)}</p>${r.reply?`<div class="notice">${esc(r.reply)}</div>`:''}${me?.admin&&r.status==='pendiente'?btn('resolve-request','Responder solicitud','secondary',`data-id="${esc(r.id)}"`):''}</article>`).join('')||empty('No hay solicitudes pendientes','Las solicitudes de los clientes se mostrarán aquí.');}
function settings(){return `<div class="settings-grid"><section class="panel"><h2>Tu cuenta</h2><p>${esc(me?.name)}<br>${esc(me?.email)}</p><p class="fine">El acceso se valida con Google. Los permisos administrativos solo los asigna el responsable del sistema.</p>${btn('logout','Cerrar sesión')}</section><section class="panel"><h2>Notificaciones</h2><p>Recibe avisos de tus trabajos y próximas revisiones en este dispositivo.</p>${btn('notifications','Activar notificaciones','primary')}${btn('disable-notifications','Desactivar avisos push')}<p class="fine">Los avisos dentro del portal seguirán disponibles. La entrega push depende de tu dispositivo y permisos.</p></section><section class="panel"><h2>Siempre a mano</h2><p>Instala el portal como una app para abrirlo desde tu pantalla de inicio.</p>${btn('install','Instalar aplicación','primary')}</section><section class="panel"><h2>Privacidad y datos</h2><p>Puedes solicitar una copia o la eliminación de tu cuenta. El equipo revisará los registros que deban conservarse.</p><a href="/portal/privacidad.html" target="_blank" rel="noopener">Leer aviso de privacidad ↗</a><div class="actions">${btn('export-request','Solicitar mis datos')}${btn('delete-request','Solicitar eliminación')}</div></section></div>`;}
function clients(){return `<div class="section-title"><p>Registra un cliente junto con su vehículo, aunque todavía no tenga cuenta.</p>${btn('new-vehicle','+ Cliente y vehículo','primary')}</div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Correo o teléfono</th><th>Registro</th><th>Placa declarada</th><th>Acción</th></tr></thead><tbody>${data.users.filter(matches).map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email||u.phone)}</td><td>${u.accountStatus==='pending'?'Contacto · sin acceso':'Cuenta registrada'}</td><td>${esc(u.registrationPlate||'Pendiente')}</td><td>${btn('new-vehicle','Registrar vehículo','secondary',`data-owner="${esc(u.id)}"`)}</td></tr>`).join('')}</tbody></table></div>${more('users')}`;}
function render(){if(!me){loginView();return;}const admin=me.admin;const nav=[['resumen','◫','Resumen'],['vehiculos','◇','Vehículos'],['trabajos','▤','Trabajos'],['mantenimientos','▦','Mantenimientos'],['pagos','$','Pagos'],['avisos','◉','Avisos'],...(admin?[['clientes','◎','Clientes'],['solicitudes','↗','Solicitudes'],['actividad','≡','Actividad']]:[]),['ajustes','⚙','Mi cuenta']];const title=nav.find(n=>n[0]===page)?.[2]||'Resumen';const body=page==='resumen'?overview():page==='vehiculos'?vehicles():page==='trabajos'?jobs():page==='mantenimientos'?maintenance():page==='pagos'?payments():page==='avisos'?notices():page==='ajustes'?settings():page==='clientes'?clients():page==='solicitudes'?requestsList():`<div class="panel"><h2>Registro de cambios</h2>${data.audit.map(a=>`<p>${esc(a.action)} · ${date(a.createdAt)} <small>${esc(a.entityId)}</small></p>`).join('')||'<p>Aún no hay cambios registrados.</p>'}${more('audit')}</div>`;
 root.innerHTML=`<div class="app-shell"><aside class="sidebar">${brandLink}<div class="workspace-label">${admin?'ADMINISTRACIÓN':'MI ESPACIO'}</div><nav aria-label="Portal">${nav.map(([key,icon,label])=>`<a href="#${key}" class="${page===key?'active':''}" ${page===key?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}${key==='avisos'&&data.notifications.some(n=>!n.read)?'<i class="unread"></i>':''}</a>`).join('')}</nav><div class="sidebar-bottom"><a href="/">↖ Sitio informativo</a>${btn('logout','Salir de mi cuenta','ghost')}</div></aside><main class="workspace"><header class="topbar">${brandLink}<span class="portal-area">${admin?'Administración':'Portal de clientes'}</span><button class="account-avatar" data-action="account" aria-label="Abrir mi cuenta">${esc(String(me.name).charAt(0).toUpperCase())}</button></header><div class="content">${demo?`<div class="demo-banner">Vista previa local · datos ficticios · sin cobros ni envíos ${btn('switch-demo',admin?'Ver como cliente':'Ver administración','ghost')}</div>`:''}<div class="page-heading"><div><span class="eyebrow">${admin?'TODO BAJO CONTROL':'EL CUIDADO ESTÁ EN LOS DETALLES'}</span><h1>${page==='resumen'?(admin?'Un buen día para cuidar.':`Hola, ${esc(me.name.split(' ')[0])}.`):title}</h1><p>${page==='resumen'?'Esto es lo que está pasando con tus vehículos.':'Detailing Experts · Cartagena'}</p></div>${btn('refresh','↻ Actualizar')}</div>${['vehiculos','trabajos','pagos','clientes','solicitudes'].includes(page)?'<label class="search-label">Buscar en los registros cargados<input id="search" type="search" placeholder="Buscar…" value="'+esc(query)+'"></label>':''}${body}<div class="install-strip"><span><strong>Tu portal, siempre a mano.</strong> Instálalo en tu celular para volver fácilmente.</span>${btn('install','Instalar app ↗')}</div><footer class="workspace-footer">Detailing Experts · Portal privado <a href="/portal/privacidad.html">Privacidad</a></footer></div></main></div>`;bind();const navigation=root.querySelector<HTMLElement>('.sidebar nav');const active=navigation?.querySelector<HTMLElement>('a.active');if(navigation&&active)navigation.scrollLeft=active.offsetLeft-navigation.offsetLeft-(navigation.clientWidth-active.offsetWidth)/2;}
function modal(title:string,content:string){document.querySelector('dialog')?.remove();const dialog=document.createElement('dialog');dialog.innerHTML=`<div class="dialog-heading"><h2>${title}</h2>${btn('close','✕','icon-button','aria-label="Cerrar"')}</div>${content}`;root.append(dialog);dialog.showModal();bind(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});}
const input=(name:string,label:string,value:unknown='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name:string,label:string,options:[string,string][],value='')=>`<label>${label}<select name="${name}" required>${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
const formFooter=()=>'<p class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" data-action="close" class="secondary">Cancelar</button><button type="submit" class="primary">Guardar</button></div>';
function jobForm(existing?:Row){if(!data.vehicles.length){toast('Registra primero un vehículo para un cliente.');return;}const j=existing||{};const local=j.appointmentAt?new Date(new Date(j.appointmentAt).getTime()-5*3600000).toISOString().slice(0,16):'';modal(existing?'Editar trabajo':'Nuevo trabajo',`<form id="job-form" data-id="${esc(j.id||'')}"><div class="form-grid">${select('vehicleId','Vehículo',data.vehicles.map(v=>[v.id,`${v.plate} · ${v.brand} ${v.model}`]),j.vehicleId)}${input('service','Servicio',j.service||'','text','required maxlength="120"')}${select('status','Estado',Object.entries(labels).filter(([k])=>['programado','en_proceso','listo','entregado','atrasado','cancelado'].includes(k)) as [string,string][],j.status||'programado')}${input('deadline','Fecha límite de entrega',j.deadline||today(),'date','required')}${input('appointment','Cita confirmada · hora Colombia',local,'datetime-local')}${input('nextReview','Próxima revisión recomendada',j.nextReview,'date')}${input('warrantyUntil','Garantía hasta',j.warrantyUntil,'date')}${input('assignedTo','Responsable',j.assignedTo,'text','maxlength="100"')}</div><label>Notas visibles para el cliente<textarea name="notes" maxlength="3000">${esc(j.notes)}</textarea></label><label>Checklist · una tarea por línea<textarea name="checklist" maxlength="2000">${esc((j.checklist||[{label:'Inspección de ingreso',done:false},{label:'Control de calidad',done:false}]).map((c:Row)=>(c.done?'[x] ':'[ ] ')+c.label).join('\n'))}</textarea></label><p class="fine">Marca [x] para una tarea completada. Un máximo de 20 tareas. No incluyas información interna en las notas.</p>${formFooter()}</form>`);}
async function jobDetail(key:string){const j=data.jobs.find(j=>j.id===key);if(!j)return;modal(esc(j.service),`<div class="row">${pill(stateLabel(j))}<span>${esc(carName(j.vehicleId))}</span></div><div class="detail-grid"><div><small>Fecha límite</small><strong>${date(j.deadline)}</strong></div><div><small>Próxima revisión</small><strong>${date(j.nextReview)}</strong></div><div><small>Garantía</small><strong>${date(j.warrantyUntil)}</strong></div></div><p class="notes">${esc(j.notes||'Sin observaciones adicionales.')}</p><h3>Control del trabajo</h3><ul class="checklist">${(j.checklist||[]).map((c:Row)=>`<li>${c.done?'✓':'○'} ${esc(c.label)}</li>`).join('')||'<li>El equipo aún no ha agregado tareas.</li>'}</ul><h3>Fotografías del trabajo</h3><div id="photo-list" class="photo-grid"><p>Cargando fotografías…</p></div>${me?.admin?`<div class="actions">${btn('edit-job','Editar trabajo','primary',`data-id="${esc(j.id)}"`)}${btn('upload-photo','Subir fotos','secondary',`data-id="${esc(j.id)}" ${!serverStatus.photos&&!demo?'disabled':''}`)}</div>`:''}`);const photos=demo?{items:[]}:await api('photos',undefined,{jobId:key});const list=document.querySelector('#photo-list');if(list)list.innerHTML=photos.items.map((p:Row)=>`<figure><img src="${esc(p.url)}" alt="${esc(p.caption||'Fotografía del trabajo')}" loading="lazy" referrerpolicy="no-referrer"><figcaption>${esc(p.stage)} · ${esc(p.caption)}</figcaption></figure>`).join('')||'<p class="fine">Aún no se han registrado fotos de este trabajo.</p>';}
async function save(action:string,body:unknown){if(demo){toast('Demostración: no se guardaron cambios ni se enviaron datos.');document.querySelector('dialog')?.close();return;}await api(action,body);await load();render();toast('Cambios guardados.');}
function bind(scope:ParentNode=root){scope.querySelectorAll<HTMLElement>('[data-action]').forEach(el=>el.addEventListener('click',async()=>{if(busy)return;try{await act(el.dataset.action!,el);}catch(e){toast(e instanceof Error?e.message:'Ocurrió un error.');}}));scope.querySelector<HTMLInputElement>('#search')?.addEventListener('input',e=>{query=(e.target as HTMLInputElement).value;const pos=query.length;render();const s=document.querySelector<HTMLInputElement>('#search');s?.focus();s?.setSelectionRange?.(pos,pos);});scope.querySelectorAll<HTMLFormElement>('form').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const submit=f.querySelector<HTMLButtonElement>('[type=submit]')!;submit.disabled=true;try{await submitForm(f);}catch(error){f.querySelector('.form-error')!.textContent=error instanceof Error?error.message:'No se pudo guardar.';}finally{busy=false;submit.disabled=false;}}));}
async function act(action:string,el:HTMLElement){const key=el.dataset.id||'';
 if(action==='login'){if(!document.querySelector<HTMLInputElement>('#consent')?.checked){toast('Lee y acepta el aviso de privacidad para continuar.');return;}sessionStorage.setItem('portal-consent','true');await login();}
 if(action==='demo-client'||action==='demo-admin'||action==='switch-demo'){if(!import.meta.env.DEV)return;demo=true;const admin=action==='demo-admin'||action==='switch-demo'&&!me?.admin;const {demoData}=await import('./demo');const d=demoData(admin);me=d.me;const {me:demoMe,...collections}=d;data=collections;serverStatus={payments:false,photos:true};view();}
 if(action==='logout'){if(!demo)await logout();demo=false;me=null;data={vehicles:[],jobs:[],invoices:[],requests:[],notifications:[],users:[],audit:[]};cursors={};loginView();}
 if(action==='account')location.hash='ajustes';
 if(action==='refresh'){await load();render();toast(demo?'Estás viendo datos de demostración.':'Información actualizada.');}
 if(action==='close')document.querySelector('dialog')?.close();
 if(action==='install'){if(matchMedia('(display-mode: standalone)').matches){toast('Ya estás usando la aplicación instalada.');return;}if(installPrompt){await installPrompt.prompt();installPrompt=null;}else modal('Instala tu portal',`<p><strong>En iPhone:</strong> abre este portal en Safari, toca Compartir y elige “Añadir a pantalla de inicio”.</p><p><strong>En Android:</strong> abre el menú de Chrome y elige “Instalar aplicación” o “Añadir a pantalla de inicio”.</p><p class="fine">La instalación requiere un navegador compatible. Podrás seguir usando el portal en la web.</p>`);}
 if(action==='notifications'){if(demo){toast('La demostración no activa notificaciones.');return;}await notifications();toast('Notificaciones activadas para este dispositivo.');}
 if(action==='disable-notifications')await save('preferences',{notifications:false});
 if(action==='delete-request'||action==='export-request')modal(action==='delete-request'?'Solicitar eliminación':'Solicitar copia de datos',`<form id="privacy-form" data-type="${action==='delete-request'?'delete':'export'}"><p>El equipo recibirá la solicitud asociada a tu cuenta y revisará los datos y obligaciones de conservación antes de responder.</p>${formFooter()}</form>`);
 if(action==='pay'){if(demo)return;const r=await api('checkout',{id:key});const url=new URL(r.url);if(url.origin!=='https://checkout.wompi.co')throw new Error('Destino de pago inválido.');location.assign(url.href);}
 if(action==='read'){if(demo){data.notifications.find(n=>n.id===key)!.read=true;render();return;}await save('read-notification',{id:key});}
 if(action==='load-more'){if(demo)return;const c=el.dataset.collection!;const result=await api('list',undefined,{collection:c,cursor:cursors[c]!});data[c]=[...data[c],...result.items];cursors[c]=result.nextCursor;render();}
 if(action==='filter'){const filter=el.dataset.filter;document.querySelector('#job-list')!.innerHTML=data.jobs.filter(matches).filter(j=>filter==='todos'||stateLabel(j)===filter).map(jobCard).join('')||empty('Sin resultados','No hay trabajos con este estado.');bind(document.querySelector('#job-list')!);root.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b===el));}
 if(action==='job-detail')await jobDetail(key);
 if(!me?.admin&&['new-job','edit-job','new-vehicle','new-invoice','resolve-request','upload-photo'].includes(action))throw new Error('Acceso reservado a administración.');
 if(action==='new-job')jobForm();if(action==='edit-job')jobForm(data.jobs.find(j=>j.id===key));
 if(action==='new-vehicle'){
  modal('Registrar vehículo',`<form id="vehicle-form"><h3>Datos del vehículo</h3><div class="form-grid">${input('plate','Placa','','text','required maxlength="10" autocomplete="off" placeholder="ABC123"')}${input('brand','Marca','','text','required maxlength="60" placeholder="Toyota"')}${input('model','Modelo','','text','required maxlength="80" placeholder="Corolla"')}${input('year','Año',new Date().getFullYear(),'number','required min="1900" max="2100"')}${input('color','Color','','text','maxlength="50"')}</div><h3>Propietario</h3>${select('ownerId','Cliente',[['','Crear cliente nuevo'],...data.users.map(u=>[u.id,u.name+' · '+(u.phone||u.email||'Sin contacto')] as [string,string])],el.dataset.owner)}<fieldset id="new-customer"><legend>Datos del cliente nuevo</legend><div class="form-grid">${input('customerName','Nombre completo','','text','required maxlength="120" autocomplete="name"')}${input('customerPhone','Teléfono / WhatsApp','','tel','required maxlength="24" autocomplete="tel" placeholder="+57 300 123 4567"')}${input('customerEmail','Correo electrónico (opcional)','','email','maxlength="254" autocomplete="email"')}</div><p class="fine">Puedes crear trabajos y programar revisiones desde ahora. Este contacto no tendrá acceso al portal hasta que el equipo vincule su cuenta verificada.</p></fieldset>${formFooter()}</form>`);
  const form=document.querySelector<HTMLFormElement>('#vehicle-form')!;const owner=form.elements.namedItem('ownerId') as HTMLSelectElement;owner.required=false;const group=form.querySelector<HTMLFieldSetElement>('#new-customer')!;const toggle=()=>{group.disabled=!!owner.value;group.hidden=!!owner.value;};owner.addEventListener('change',toggle);toggle();
 }
 if(action==='new-invoice'){if(!data.jobs.length){toast('Registra primero el trabajo.');return;}modal('Crear cobro',`<form id="invoice-form">${select('jobId','Trabajo',data.jobs.map(j=>[j.id,`${j.service} · ${carName(j.vehicleId)}`]))}${input('description','Concepto','','text','required maxlength="150"')}${input('amount','Valor en pesos colombianos','','number','required min="100" max="20000000" step="1"')}${input('dueDate','Fecha de vencimiento',today(),'date','required')}<p class="fine">El cobro se registra en el portal. No se realiza ningún cargo automático a la tarjeta.</p>${formFooter()}</form>`);}
 if(action==='new-request'){if(!data.vehicles.length){toast('El equipo debe vincular tu vehículo primero.');return;}modal('Solicitar una cita',`<form id="request-form">${select('vehicleId','Vehículo',data.vehicles.map(v=>[v.id,`${v.brand} ${v.model} · ${v.plate}`]))}${input('preferredDate','Fecha que prefieres','','date',`required min="${today()}"`)}<label>¿Qué necesitas?<textarea name="reason" required maxlength="1000"></textarea></label><p class="fine">El equipo revisará disponibilidad. Tu cita quedará confirmada cuando aparezca registrada en el trabajo.</p>${formFooter()}</form>`);}
 if(action==='resolve-request')modal('Responder solicitud',`<form id="resolve-form" data-id="${esc(key)}">${select('status','Respuesta',[['atendida','Atendida'],['rechazada','No disponible']])}<label>Mensaje para el cliente<textarea name="reply" required maxlength="1000"></textarea></label><p class="fine">Para confirmar una cita, registra también su fecha y hora en el trabajo.</p>${formFooter()}</form>`);
 if(action==='upload-photo')modal('Fotografías del trabajo',`<form id="photo-form" data-id="${esc(key)}">${select('stage','Etapa',[['antes','Antes'],['proceso','En proceso'],['despues','Después']])}${input('caption','Descripción','','text','maxlength="200"')}<label>Selecciona hasta 5 fotos<input type="file" name="photos" accept="image/jpeg,image/png,image/webp" multiple required></label><div class="notice">Compresión automática: hasta 1600 px, formato WebP y máximo 1 MB por foto. Se eliminan los metadatos de ubicación.</div><p id="upload-progress" role="status"></p>${formFooter()}</form>`);
}
async function submitForm(form:HTMLFormElement){const fields=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;const key=form.dataset.id;
 if(form.id==='vehicle-form'){
  const {customerName,customerPhone,customerEmail,ownerId,...rest}=fields;const vehicleData={...rest,year:Number(fields.year)};
  if(ownerId)await save('vehicle',{data:{...vehicleData,ownerId}});
  else await save('customer-vehicle',{customer:{name:customerName,phone:customerPhone,email:customerEmail||''},vehicle:vehicleData});
 }
 if(form.id==='job-form'){const old=data.jobs.find(j=>j.id===key);const v=vehicle(fields.vehicleId)!;const checklist=fields.checklist.split('\n').map(s=>s.trim()).filter(Boolean).map(s=>({label:s.replace(/^\[[ xX]\]\s*/,''),done:/^\[[xX]\]/.test(s)}));const {appointment,...rest}=fields;await save('job',{id:key||undefined,version:old?.updatedAt,data:{...rest,ownerId:v.ownerId,checklist,appointmentAt:appointment?new Date(appointment+'-05:00').toISOString():''}});}
 if(form.id==='invoice-form'){const job=data.jobs.find(j=>j.id===fields.jobId)!;await save('invoice',{data:{jobId:fields.jobId,ownerId:job.ownerId,description:fields.description,amountCents:Math.round(Number(fields.amount)*100),dueDate:fields.dueDate}});}
 if(form.id==='request-form')await save('request',fields);
 if(form.id==='resolve-form')await save('resolve-request',{id:key,...fields});
 if(form.id==='privacy-form')await save('privacy-request',{type:form.dataset.type});
 if(form.id==='photo-form'){if(demo){toast('Demostración: no se han subido archivos.');return;}const files=Array.from(form.querySelector<HTMLInputElement>('[name=photos]')!.files||[]);if(files.length>5)throw new Error('Selecciona un máximo de 5 fotos por carga.');let done=0;for(const file of files){const compressed=await compressPhoto(file);form.querySelector('#upload-progress')!.textContent=`Subiendo ${done+1}/${files.length}: ${Math.round(compressed.bytes/1024)} KB (original ${Math.round(compressed.original/1024)} KB)`;await api('upload',{jobId:key,stage:fields.stage,caption:fields.caption,base64:compressed.base64},{},'/api/photo');done++;}toast(`${done} fotos comprimidas y guardadas.`);await jobDetail(key!);}
}
async function openAccount(user:any){if(!user){me=null;loginView();return;}if(!user.emailVerified&&!user.phoneNumber){registrationView(root,false,()=>openAccount(user));return;}try{const info=await api('me');if(!info.admin&&!info.profile?.registrationPlate){registrationView(root,true,()=>openAccount(user));return;}me=info;demo=false;await load();view();}catch(e){me=null;loginView();toast(e instanceof Error?e.message:'No se pudo abrir tu cuenta.');}}
async function start(){try{serverStatus=await api('status');}catch{serverStatus={};}setup(user=>{void openAccount(user);});if('serviceWorker'in navigator)navigator.serviceWorker.register('/portal/sw.js',{scope:'/portal/'}).catch(()=>{});}
void start();
